version: "3"
services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    depends_on:
      - postgres
    environment:
      SECRET: "my-super-secret-key-123"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"

volumes:
  postgres_data: